### ISSUE TITLE
docker 安装 paddlespeech时，测试单卡没问题，多卡测试时报 Bus error (core dumped)

### ISSUE THREAD

**Issue by wangdabee** [PaddlePaddle/PaddleCloud#707]
按照提供的dockerfile安装后， paddle.utils.run_check() 测试显卡时，出现以下报错：

`Python 3.7.13 (default, Aug 25 2022, 17:42:24)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

import paddle
paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0826 13:33:08.306574 4132 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0826 13:33:08.310814 4132 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
PaddlePaddle works well on 1 GPU.
W0826 13:33:10.297623 4132 parallel_executor.cc:642] Cannot enable P2P access from 0 to 1
W0826 13:33:10.297649 4132 parallel_executor.cc:642] Cannot enable P2P access from 1 to 0
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0

C++ Traceback (most recent call last):
No stack trace in paddle, may be caused by external reasons.

Error Message Summary:
FatalError: Access to an undefined portion of a memory object is detected by the operating system.
[TimeInfo: *** Aborted at 1661491991 (unix time) try "date -d @1661491991" if you are using GNU date ***]
[SignalInfo: *** SIGBUS (@0x7f59a9dd8000) received by PID 4132 (TID 0x7f5b04cd0700) from PID 18446744072264450048 ***]

Bus error (core dumped)`

并在当前目录下生成 core.* 文件
请问该如何解决？谢谢。

**Comment by freeliuzc** [comment]
你好，请问是按照哪个 Dockerfile 安装的？是这个吗[[PaddleCloud](https://github.com/PaddlePaddle/PaddleCloud)/[tekton](https://github.com/PaddlePaddle/PaddleCloud/tree/main/tekton)/dockerfiles/](https://github.com/PaddlePaddle/PaddleCloud/blob/main/tekton/dockerfiles/Dockerfile.speech)

**Comment by freeliuzc** [comment]
1. 您好，请问是按照这个安装的吗？ https://github.com/PaddlePaddle/PaddleCloud/blob/main/tekton/dockerfiles/Dockerfile.speech
2. 可以试下我们制作的镜像是否有同样问题 https://hub.docker.com/r/paddlecloud/paddlespeech 
3. 如果2中的镜像还有同样的问题，请提供下具体的机器/GPU环境

**Comment by wangdabee** [comment]
是用的paddlecloud提供的第一个docker安装的，安装的是匹配显卡cuda的（单卡测试没问题）
我怀疑有可能的原因是  宿主机是centos7 x86_64 架构的   然后docker里是amd64架构的  是不是和这个有关系 或者 docker里面提供的nccl是amd64架构的 和宿主机的架构不一致？ 我后来也试了下安装amd64架构的nccl  可是依旧报这个bug

**Comment by freeliuzc** [comment]
麻烦试下 registry.baidubce.com/paddleflow-public/paddlespeech:develop-gpu-cuda11.2-cudnn8-latest / paddlecloud/paddlespeech:develop-gpu-cuda11.2-cudnn8-latest 这两个中的任一镜像是否有此问题

**Comment by freeliuzc** [comment]
Hi，你好，在多卡环境测试了下，无法复现你的问题
1. 确定下物理机是否正确安装了 nvidia 驱动，有在物理机试过使用多卡吗？
2. 看你检测时，gcc 是5.4，环境和我们提供的镜像应该是不一样，麻烦试下 registry.baidubce.com/paddleflow-public/paddlespeech:develop-gpu-cuda11.2-cudnn8-latest / paddlecloud/paddlespeech:develop-gpu-cuda11.2-cudnn8-latest 这两个中的任一镜像是否有此问题
3. 2中的镜像在8张 v100的 Cenos7 测试结果；有可能是物理机的 GPU 本身环境有问题
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```
```
Python 3.7.13 (default, Apr 24 2022, 01:04:09)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0829 03:05:07.244967    11 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.4, Runtime API Version: 11.2
W0829 03:05:07.254874    11 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
PaddlePaddle works well on 1 GPU.
W0829 03:05:34.706579    11 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 8 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

**Comment by wangdabee** [comment]
找到问题了 是因为/dev/shm 默认的是64M，内存太小  
解决方法为 在nvidia-docker run 的时候指定 --shm-size 4G 即可。
谢谢。
